public class BaseReport
{
    public int ReportId { get; set; }
    public string ReportName { get; set; }
    public DateTime CreatedDate { get; set; }
    public string CreatedBy { get; set; }
    
    public BaseReport() : this(0, "<title>","<none>") 
    {

    }
    public BaseReport(int reportId, string reportName, string createdBy)
    {
        ReportId = reportId;
        ReportName = reportName;
        CreatedBy = createdBy;
        CreatedDate = DateTime.Now;
    }

    public string GenerateReport()
    {
        return $"Report '{ReportName}' generated by {CreatedBy} on {CreatedDate}.";
    }

    public void PrintReport()
    {
        // Logic to print the report
        Console.WriteLine(GenerateReport());
    }
}