public class ReportManagerBO : IReportManagerBO
{
    private BaseReport _baseReport;

    public int ReportId { get; set; }
    public string ReportName { get; set; }
    public DateTime CreatedDate { get; set; }
    public string CreatedBy { get; set; }

    public ReportManagerBO() { }  

    public string GenerateReport()
    {
         if (_baseReport == null)
            {
                _baseReport = new BaseReport();
            }

        return _baseReport.GenerateReport();
        // Logic to generate the report
        //return $"Report '{ReportName}' generated by {CreatedBy} on {CreatedDate}.";
    }

    public void PrintReport()
    {
        // Logic to print the report
        //Console.WriteLine(GenerateReport());
    }
}