public class ReportManagerBO
{
    public int ReportId { get; set; }
    public string ReportName { get; set; }
    public DateTime CreatedDate { get; set; }
    public string CreatedBy { get; set; }

    public ReportManagerBO(int reportId, string reportName, string createdBy)
    {
        ReportId = reportId;
        ReportName = reportName;
        CreatedBy = createdBy;
        CreatedDate = DateTime.Now;
    }

    public string GenerateReport()
    {
        // Logic to generate the report
        //return $"Report '{ReportName}' generated by {CreatedBy} on {CreatedDate}.";
        return "Report Text 1 2 3";
    }

    public void PrintReport()
    {
        // Logic to print the report
        //Console.WriteLine(GenerateReport());
    }
}