public class ReportManagerService : IReportManagerService
{
    //private readonly IReportManagerService _reportService;

    public int ReportId { get; set; }
    public string ReportName { get; set; }
    public DateTime CreatedDate { get; set; }
    public string CreatedBy { get; set; }

    //public ReportManagerService(IReportManagerService reportService)
    //{
        //_reportService = reportService;
    //}

    public ReportManagerService() : this(0, "<title>","<none>") 
    {

    }

    public ReportManagerService(int reportId, string reportName, string createdBy)
    {
        ReportId = reportId;
        ReportName = reportName;
        CreatedBy = createdBy;
        CreatedDate = DateTime.Now;
    }

    public string GenerateReport()
    {
        //return _reportBo.GenerateReport();
        // Logic to generate the report
        return $"Report '{ReportName}' generated by {CreatedBy} on {CreatedDate}.";
    }

    public void PrintReport()
    {
        // Logic to print the report
        //Console.WriteLine(GenerateReport());
    }
}